name: push_notifications
description: A new Flutter package project.
version: 1.0.3
homepage: https://github.com/cassiomeira12/push_notifications

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: 0.13.4
  path_provider: 2.0.8 # flutter 2.5.3
  flutter_native_timezone: 2.0.0
  flutter_local_notifications: 9.4.0
  shared_preferences: 2.0.13

  firebase_core: 1.12.0 # flutter 2.5.3
  firebase_messaging: 11.2.7 # flutter 2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6 # flutter 2.5.3

flutter:
